### PR TITLE
Simplify request/response association using EventEmitter

### PR DESCRIPTION
**Pull request by shesek**
Note: using `once()` instead of `on()` ensures that the listeners are cleared after the first invocation and won't leak memory.

### CODE REVIEW

**Comment by shesek** [comment]
Note: using `once()` instead of `on()` ensures that the listeners are cleared after the first invocation and won't leak memory.

**Comment by shesek** [comment]
(forced-push updated to adhere to the xo linter rules)

**Comment by isghe** [comment]
ACK, waiting for @afilini review ;-)

**Comment by afilini** [comment]
Looks good to me, thanks for the contribution!

**Comment by isghe** [comment]
👍 thanks @shesek and @afilini

**Pull request merged**
