### PR TITLE
DRY RPC methods

### PR DESCRIPTION
**Pull request by shesek**
Note: `withdraw()` currently uses a [reversed arguments order](https://github.com/BHBNETWORK/lightning-client-js/blob/b0a1b023942e139f37150880427bc717c77e9c12/index.js#L240-L242) from the one used by c-lightning. To maintain backwards-compatibility, I special-cased `withdraw` to accept both type signatures. If the reverse order is not by-design and breaking backward-compatibility is acceptable, the special-case can be removed.

### CODE REVIEW

**Comment by shesek** [comment]
(forced-push updated to adhere to the xo linter rules, didn't notice that earlier)

**Comment by isghe** [comment]
Hi @shesek 
Yes I think it would be better to remove the backward-compatibility, with `withdraw`.
Thanks a lot :-)

**Comment by isghe** [comment]
@shesek you can proceed and remove the backward-compatibility, with withdraw, and I'll merge.
Thanks a lot :-)

**Comment by shesek** [comment]
Sure thing! One moment.

**Comment by shesek** [comment]
Force pushed in https://github.com/BHBNETWORK/lightning-client-js/pull/1/commits/64c0afcaa118c12d6c60f0bb3fc7a53ca8dee011.

**Comment by shesek** [comment]
Oops, one moment, forgot to remove `DEST_RE`.

**Comment by isghe** [comment]
👍 thanks for you contribution @shesek

**Pull request merged**
